repos:
  - repo: local
    hooks:
      - id: stylua
        name: StyLua
        language: rust
        entry: stylua
        types: [lua]
        files: '^\.config/nvim/'
        args: ["--config-path", ".config/nvim/.stylua.toml"]
