#!/usr/bin/env bash

file="$1"

if ! rg "$file" "$LF_SCROLLINGPREVIEW_TEMPDIR/offset" 2>/dev/null; then
  offset=1
else
  # Retrieve the current preview offset.
  offset="$(rg "(\d) $file" --only-matching --no-line-number --replace '$1' "$LF_SCROLLINGPREVIEW_TEMPDIR/offset" 2>/dev/null)"
fi

image_preview="$HOME/.config/lf/image"
# Clear the last preview (if any)
"$image_preview" clear

# Calculate where the image should be placed on the screen.
num=$(printf "%0.f\n" "$(echo "$(tput cols) / 2" | bc)")
numb=$(printf "%0.f\n" "$(echo "$(tput cols) - "$num" - 1" | bc)")
numc=$(printf "%0.f\n" "$(echo "$(tput lines) - 2" | bc)")

case "$file" in
  *.tgz | *.tar.gz) tar tzf "$file" ;;
  *.tar.bz2 | *.tbz2) tar tjf "$file" ;;
  *.tar.txz | *.txz) xz --list "$file" ;;
  *.tar) tar tf "$file" ;;
  *.zip | *.jar | *.war | *.ear | *.oxt) unzip -l "$file" ;;
  *.rar) unrar l "$file" ;;
  *.7z) 7z l "$file" ;;
  *.[1-8]) man "$file" | col -b ;;
  *.o) nm "$file" | less ;;
  *.torrent) transmission-show "$file" ;;
  *.iso) iso-info --no-header -l "$file" ;;
  *odt,*.ods,*.odp,*.sxw) odt2txt "$file" ;;
  *.doc) catdoc "$file" ;;
  *.docx) docx2txt "$file" - ;;
  *.csv) bat "$file" | sed s/,/\\n/g ;;
  *.pdf)
    CACHE=$(mktemp /tmp/thumbcache.XXXXX)
    pdftoppm -png -f 1 -singlefile "$file" "$CACHE"
    "$image_preview" draw "$CACHE.png" "$num" 1 "$numb" "$numc"
    ;;
  *.epub)
    CACHE=$(mktemp /tmp/thumbcache.XXXXX)
    epub-thumbnailer "$file" "$CACHE" 1024
    "$image_preview" draw "$CACHE" "$num" 1 "$numb" "$numc"
    ;;
  *.bmp | *.jpg | *.jpeg | *.png | *.xpm)
    "$image_preview" draw "$file" "$num" 1 "$numb" "$numc"
    ;;
  *.wav | *.mp3 | *.flac | *.m4a | *.wma | *.ape | *.ac3 | *.og[agx] | *.spx | *.opus | *.as[fx]) exiftool "$file" ;;
  *.avi | *.mp4 | *.wmv | *.dat | *.3gp | *.ogv | *.mkv | *.mpg | *.mpeg | *.vob | *.fl[icv] | *.m2v | *.mov | *.webm | *.ts | *.mts | *.m4v | *.r[am] | *.qt | *.divx)
    CACHE=$(mktemp /tmp/thumbcache.XXXXX)
    ffmpegthumbnailer -i "$file" -o "$CACHE" -s 0
    "$image_preview" draw "$CACHE" "$num" 1 "$numb" "$numc"
    ;;
  *.md) glow -s dark "$file" | bat ;;
  *)
    unset COLORTERM
    bat --pager='less -Rf' --color=always --number --wrap auto --paging=always --line-range "${offset}:" "$file"
    ;;
esac
