version: 2
# log-file: /tmp/efm-output.log
# log-level: 1
tools:
  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -i 2 -ci'
    format-stdin: true  
  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i --no-keep-simple-function-one-line --column-limit=120'
    format-stdin: true

languages:
  lua:
    - <<: *lua-lua-format
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
