version: 2
log-file: /tmp/efm-output.log
log-level: 1
tools:
  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
  shfmt: &shfmt
    format-command: 'shfmt -i 2 -ci'
    format-stdin: true  
  luaformat: &luaformat
    format-command: "lua-format --chop-down-table --indent-width=2 --no-use-tab --in-place --no-keep-simple-function-one-line --column-limit=80"
    format-stdin: true

languages:
  lua:
    - <<: *luaformat
  sh:
    - <<: *shellcheck
    - <<: *shfmt
  zsh:
    - <<: *shellcheck
    - <<: *shfmt
