gui:
  # stuff relating to the UI
  authorColors: {}
  branchColors: {}
  commandLogSize: 8
  expandFocusedSidePanel: false
  language: auto
  mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
  mouseEvents: true
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  showBottomLine: true
  showCommandLog: true
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: true
  showIcons: true
  showRandomTip: false
  sidePanelWidth: 0.3333 # number from 0 to 1
  skipNoStagedFilesWarning: false
  skipStashWarning: false
  skipUnstageLineWarning: false
  splitDiff: auto
  theme:
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
    cherryPickedCommitBgColor:
    - blue
    cherryPickedCommitFgColor:
    - cyan
    unstagedChangesColor:
    - red
  commitLength:
    show: true
git:
  paging:
    colorArg: always
    pager: ""
    useConfig: false
  commit:
    signOff: false
  merging:
    # only applicable to unix users
    manualCommit: false
    # extra args passed to `git merge`, e.g. --no-ff
    args: ''
  pull:
    mode: 'ff-only' # one of 'merge' | 'rebase' | 'ff-only'
  autoFetch: true
  autoRefresh: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative
    --pretty=medium {{branchName}} --
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate
    --date=relative  --pretty=medium
  overrideGpg: false # prevents lazygit from spawning a separate process when using GPG
  disableForcePushing: false
  commitPrefixes: {}
  parseEmoji: true
  log:
    order: topo-order
    showGraph: when-maximised
  diffContextSize: 3
update:
  method: prompt # can be: prompt | background | never
  days: 14 # how often an update is checked for
refresher:
  refreshInterval: 10 # file/submodule refresh interval in seconds
  fetchInterval: 60 # re-fetch interval in seconds
reporting: 'off' # one of: 'on' | 'off' | 'undetermined'
splashUpdatesIndex: 0
confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: false
services: {}
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
promptToReturnFromSubprocess: true
os:
  editCommand: 'nvim'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
  openCommand:  xdg-open {{filename}} >/dev/null
  openLinkCommand: xdg-open {{link}} >/dev/null

keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: ','
    nextPage: .
    scrollLeft: H
    scrollRight: L
    gotoTop: <
    gotoBottom: '>'
    prevBlock: <left>
    nextBlock: <right>
    prevBlock-alt: h
    nextBlock-alt: l
    nextBlock-alt2: <tab>
    prevBlock-alt2: <backtab>
    jumpToBlock:
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: /
    optionMenu: x
    optionMenu-alt1: '?'
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirm-alt1: "y"
    remove: d
    new: "n"
    edit: e
    openFile: o
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: <c-u>
    scrollDownMain-alt1: <c-d>
    executeCustomCommand: ':'
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: ']'
    prevTab: '['
    nextScreenMode: +
    prevScreenMode: _
    undo: z
    redo: <c-z>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-f>
    submitEditorText: <enter>
    appendNewline: <a-enter>
    extrasMenu: '@'
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'
  status:
    checkForUpdate: u
    recentRepos: <enter>
    allBranchesLogGraph: a
  files:
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: C
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: a
    viewResetOptions: D
    fetch: f
    toggleTreeView: '`'
    openMergeTool: M
    openStatusFilter: <c-b>
  branches:
    createPullRequest: o
    viewPullRequestOptions: O
    copyPullRequestURL: <c-y>
    checkoutBranchByName: c
    forceCheckoutBranch: F
    rebaseBranch: R
    renameBranch: r
    mergeIntoCurrentBranch: M
    viewGitFlowOptions: i
    fastForward: f
    pushTag: P
    setUpstream: u
    fetchRemote: f
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: g
    markCommitAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: J
    moveUpCommit: K
    amendToCommit: A
    resetCommitAuthor: a
    pickCommit: p
    revertCommit: t
    cherryPickCopy: c
    cherryPickCopyRange: C
    pasteCommits: v
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: <c-R>
    copyCommitAttributeToClipboard: "y"
    openLogMenu: <c-l>
    openInBrowser: o
    viewBisectOptions: b
  stash:
    popStash: g
  commitFiles:
    checkoutCommitFile: c
  main:
    toggleDragSelect: v
    toggleDragSelect-alt: V
    toggleSelectHunk: a
    pickBothHunks: b
    editSelectHunk: E
  submodules:
    init: i
    update: u
    bulkMenu: b

customCommands:
  - key: '<c-g>'
    command: "git reuse-msg"
    context: 'files'
    loadingText: 're-use last message'
  - key: '<c-r>'
    command: "git soft-reset"
    context: 'commits'
    loadingText: 'soft reset'
  - key: 'X'
    command: "git rebase --abort"
    context: 'commits'
    loadingText: 'rebase --abort'
  - key: '<c-f>'
    command: "git fetch --all"
    context: 'files'
    loadingText: 'fetch --all'
