session_name: default
windows:
- window_name: main
  panes:
    - cd ${XDG_CONFIG_HOME}
    - cd ${XDG_DATA_HOME}
- window_name: nvim
  start_directory: ${XDG_CONFIG_HOME}/nvim
  panes:
    - shell_command: nvim
- window_name: lvim
  start_directory: ${XDG_DATA_HOME}/lunarvim/lvim
  panes:
    - shell_command: lvim
- window_name: lazydots
  panes:
    - shell_command: lazydots
