require('config.barbar')
require('config.comments')
require('config.compe')
require('config.dashboard')
require('config.git')
require('config.statusline')
require('config.telescope')
require('config.tree')
require('config.treesitter')
require('config.whichkey')
require('config.formatter')
require('config.lsp-trouble')

require('spectre').setup()
