# generate completion
# rustup completions zsh cargo > ~/.local/share/zsh/site-functions/_cargo
# rustup completions zsh rustup > ~/.local/share/zsh/site-functions/_rustup


[alias]     # command aliases
ls = "install --list"
i = "install"
ia = "install-update"

[target.x86_64-unknown-linux-gnu]
rustflags = [ "-C", "linker=clang-12"]

[term]
color = 'auto'         # whether cargo colorizes output
progress.when = 'auto' # whether cargo shows progress bar
progress.width = 80    # width of progress bar

