--require('plenary.profile').start("profile.log")
require('utils')
require('default-config')
require('plugins')
require('settings')
require('autocmds')
require('keymappings')
require('config.treesitter')
require('config.whichkey')
require('lsp')
-- require'plenary.profile'.stop()
