require('plugins')
require('globals')
require('utils')

require('autocmds')
require('settings')
require('keymappings')
require('config')

---- LSP
require('lsp')
require('lsp.lua-ls')
require('lsp.bash-ls')
require('lsp.efm-general-ls')
-- require('lsp.clangd')
-- require('lsp.docker-ls')
-- require('lsp.go-ls')
-- require('lsp.json-ls')
-- require('lsp.python-ls')
-- require('lsp.rust-ls')
-- require('lsp.vim-ls')
-- require('lsp.yaml-ls')
